// 200 预设恋爱清单条目，按 8 类各 25 项
export interface SeedItem { category: string; title: string; }

export const BUCKET_SEED: SeedItem[] = [
  // 日常 (25)
  { category: '日常', title: '一起睡到自然醒' },
  { category: '日常', title: '在阳台一起看一次日落' },
  { category: '日常', title: '一起去菜市场买菜' },
  { category: '日常', title: '一起做一次大扫除' },
  { category: '日常', title: '为对方准备一次早餐' },
  { category: '日常', title: '一起遛弯一万步' },
  { category: '日常', title: '一起追完一部剧' },
  { category: '日常', title: '在沙发上抱着看老电影' },
  { category: '日常', title: '一起整理一次衣柜' },
  { category: '日常', title: '一起听一晚电台' },
  { category: '日常', title: '一起午睡' },
  { category: '日常', title: '一起逛超市买零食' },
  { category: '日常', title: '一起吃一次火锅外卖' },
  { category: '日常', title: '在家一起拼一幅拼图' },
  { category: '日常', title: '一起在家看星空' },
  { category: '日常', title: '一起养一盆植物' },
  { category: '日常', title: '互相按摩肩颈十分钟' },
  { category: '日常', title: '一起挑一束花放家里' },
  { category: '日常', title: '一起换一次床单被套' },
  { category: '日常', title: '一起做一次瑜伽' },
  { category: '日常', title: '互相剪一次指甲' },
  { category: '日常', title: '一起在阳台喝下午茶' },
  { category: '日常', title: '一起读完一本书' },
  { category: '日常', title: '雨天一起窝在被窝里' },
  { category: '日常', title: '一起做一晚扎染或手账' },

  // 约会 (25)
  { category: '约会', title: '一起看一场电影' },
  { category: '约会', title: '去一次密室逃脱' },
  { category: '约会', title: '一起去剧本杀' },
  { category: '约会', title: '一起去看一次演唱会' },
  { category: '约会', title: '一起去看一次话剧' },
  { category: '约会', title: '在江边吹晚风' },
  { category: '约会', title: '一起看一次脱口秀' },
  { category: '约会', title: '一起去美术馆' },
  { category: '约会', title: '一起去博物馆' },
  { category: '约会', title: '一起逛一次书店' },
  { category: '约会', title: '一起逛一次夜市' },
  { category: '约会', title: '一起在公园野餐' },
  { category: '约会', title: '一起去摩天轮顶端拥抱' },
  { category: '约会', title: '一起放一次烟花或孔明灯' },
  { category: '约会', title: '一起去 Live House' },
  { category: '约会', title: '在咖啡馆共度一个下午' },
  { category: '约会', title: '在大排档吃宵夜到凌晨' },
  { category: '约会', title: '一起去看一次球赛' },
  { category: '约会', title: '一起逛一次古董/旧物市场' },
  { category: '约会', title: '一起去看一场画展' },
  { category: '约会', title: '一起去打一次保龄球' },
  { category: '约会', title: '一起打一次台球' },
  { category: '约会', title: '一起去射箭/飞镖' },
  { category: '约会', title: '一起去 KTV 唱到沙哑' },
  { category: '约会', title: '一起在天台数星星' },

  // 美食 (25)
  { category: '美食', title: '一起在家做饺子' },
  { category: '美食', title: '一起做一次早餐三明治' },
  { category: '美食', title: '一起烤一次蛋糕' },
  { category: '美食', title: '一起烤一次饼干' },
  { category: '美食', title: '一起做一次寿司' },
  { category: '美食', title: '一起做一桌团圆饭' },
  { category: '美食', title: '一起吃一次米其林餐厅' },
  { category: '美食', title: '一起喝一次精酿啤酒' },
  { category: '美食', title: '一起去一次酒吧微醺' },
  { category: '美食', title: '一起喝同一杯奶茶' },
  { category: '美食', title: '一起尝一次没吃过的菜系' },
  { category: '美食', title: '一起去吃一次自助餐' },
  { category: '美食', title: '一起做一次炒饭比赛' },
  { category: '美食', title: '一起做一杯手冲咖啡' },
  { category: '美食', title: '一起做一次披萨' },
  { category: '美食', title: '一起包一次馄饨' },
  { category: '美食', title: '一起做一次麻辣烫' },
  { category: '美食', title: '一起夜里吃一次方便面加蛋' },
  { category: '美食', title: '一起做一次烧烤' },
  { category: '美食', title: '一起在江边吃小龙虾' },
  { category: '美食', title: '一起做一次冰淇淋或刨冰' },
  { category: '美食', title: '一起喝一次下午茶套餐' },
  { category: '美食', title: '一起在家做一次糖水' },
  { category: '美食', title: '一起做一次牛排晚餐' },
  { category: '美食', title: '一起去尝一次街边小店' },

  // 旅行 (25)
  { category: '旅行', title: '一起去看一次大海' },
  { category: '旅行', title: '一起去爬一座山看日出' },
  { category: '旅行', title: '一起来一次说走就走的周末游' },
  { category: '旅行', title: '一起去一次草原' },
  { category: '旅行', title: '一起去一次沙漠' },
  { category: '旅行', title: '一起去一次雪山' },
  { category: '旅行', title: '一起体验一次温泉' },
  { category: '旅行', title: '一起住一次海景民宿' },
  { category: '旅行', title: '一起住一次森林木屋' },
  { category: '旅行', title: '一起来一次自驾游' },
  { category: '旅行', title: '一起坐一次绿皮火车' },
  { category: '旅行', title: '一起去一次古镇过夜' },
  { category: '旅行', title: '一起去一次海岛潜水' },
  { category: '旅行', title: '一起出一次国' },
  { category: '旅行', title: '一起去看一次极光' },
  { category: '旅行', title: '一起去看一次樱花' },
  { category: '旅行', title: '一起去看一次薰衣草田' },
  { category: '旅行', title: '一起去看一次银杏季' },
  { category: '旅行', title: '一起去看一次秋枫' },
  { category: '旅行', title: '一起去一次迪士尼或环球影城' },
  { category: '旅行', title: '一起去一次宠物乐园或动物园' },
  { category: '旅行', title: '一起去一次海洋馆' },
  { category: '旅行', title: '一起去一次植物园' },
  { category: '旅行', title: '一起去一次花海' },
  { category: '旅行', title: '一起去一次跨年夜的城市' },

  // 惊喜 (25)
  { category: '惊喜', title: '送对方一个手写情书' },
  { category: '惊喜', title: '为对方准备一束花' },
  { category: '惊喜', title: '为对方准备一次盲盒礼物' },
  { category: '惊喜', title: '凌晨给对方做一次夜宵' },
  { category: '惊喜', title: '为对方录一段告白视频' },
  { category: '惊喜', title: '给对方画一幅画像' },
  { category: '惊喜', title: '送对方一份生日蛋糕惊喜' },
  { category: '惊喜', title: '为对方准备一次烛光晚餐' },
  { category: '惊喜', title: '一起完成一次惊喜求婚（或被求婚）' },
  { category: '惊喜', title: '送对方一封未来的信' },
  { category: '惊喜', title: '为对方做一次主题房间' },
  { category: '惊喜', title: '准备一次周年纪念派对' },
  { category: '惊喜', title: '给对方写满一本日记' },
  { category: '惊喜', title: '在重要日子送一份手工礼物' },
  { category: '惊喜', title: '为对方煮一碗长寿面' },
  { category: '惊喜', title: '在工作日给对方送一束花到公司' },
  { category: '惊喜', title: '深夜接对方下班一次' },
  { category: '惊喜', title: '请对方家人吃一次饭' },
  { category: '惊喜', title: '在朋友圈/动态公开表白一次' },
  { category: '惊喜', title: '为对方策划一次主题旅行' },
  { category: '惊喜', title: '在车里准备一份生日小蛋糕' },
  { category: '惊喜', title: '为对方做一次专属歌单' },
  { category: '惊喜', title: '为对方做一份照片回忆视频' },
  { category: '惊喜', title: '为对方准备一份匿名小礼物' },
  { category: '惊喜', title: '在异地为对方点一份外卖' },

  // 成长 (25)
  { category: '成长', title: '一起读一本同样的书并讨论' },
  { category: '成长', title: '一起背一次单词坚持一周' },
  { category: '成长', title: '一起报一门兴趣课' },
  { category: '成长', title: '一起完成一次健身计划' },
  { category: '成长', title: '一起参加一次公益活动' },
  { category: '成长', title: '一起捐一次血' },
  { category: '成长', title: '一起做一次义工' },
  { category: '成长', title: '一起学做一道新菜' },
  { category: '成长', title: '一起学一首歌的合唱' },
  { category: '成长', title: '一起学一支舞' },
  { category: '成长', title: '一起学一门小语种打招呼' },
  { category: '成长', title: '一起拍一次摄影作品' },
  { category: '成长', title: '一起完成一次断舍离' },
  { category: '成长', title: '一起做一次理财规划' },
  { category: '成长', title: '一起列一份共同愿望清单' },
  { category: '成长', title: '一起复盘一次过去一年' },
  { category: '成长', title: '一起戒一次坏习惯' },
  { category: '成长', title: '一起完成一次 21 天挑战' },
  { category: '成长', title: '一起背一首长诗' },
  { category: '成长', title: '一起练一次冥想' },
  { category: '成长', title: '一起学一次心肺复苏' },
  { category: '成长', title: '一起完成一次健康体检' },
  { category: '成长', title: '一起学一个魔术' },
  { category: '成长', title: '一起读一次心理学测评' },
  { category: '成长', title: '一起完成一次彼此的访谈记录' },

  // 挑战 (25)
  { category: '挑战', title: '一起跑一次 5 公里' },
  { category: '挑战', title: '一起跑一次半马' },
  { category: '挑战', title: '一起完成一次徒步' },
  { category: '挑战', title: '一起骑一次长途自行车' },
  { category: '挑战', title: '一起去蹦极' },
  { category: '挑战', title: '一起玩一次跳伞' },
  { category: '挑战', title: '一起体验一次滑翔伞' },
  { category: '挑战', title: '一起体验一次冲浪' },
  { category: '挑战', title: '一起体验一次滑雪' },
  { category: '挑战', title: '一起体验一次滑板' },
  { category: '挑战', title: '一起去一次攀岩' },
  { category: '挑战', title: '一起体验一次卡丁车' },
  { category: '挑战', title: '一起来一次彩弹/真人 CS' },
  { category: '挑战', title: '一起完成一次水上乐园' },
  { category: '挑战', title: '一起跨年倒数零点接吻' },
  { category: '挑战', title: '一起完成一次马拉松接力' },
  { category: '挑战', title: '一起完成一次远途自驾' },
  { category: '挑战', title: '一起考到一个共同证书' },
  { category: '挑战', title: '一起完成一次深夜骑行' },
  { category: '挑战', title: '一起在沙滩看完一次日出' },
  { category: '挑战', title: '一起体验一次皮划艇' },
  { category: '挑战', title: '一起夜爬一次山' },
  { category: '挑战', title: '一起完成一次拼车长途旅行' },
  { category: '挑战', title: '一起完成一次浮潜' },
  { category: '挑战', title: '一起完成一次登顶合影' },

  // 纪念 (25)
  { category: '纪念', title: '一起拍一组情侣写真' },
  { category: '纪念', title: '一起拍一组婚纱照' },
  { category: '纪念', title: '一起做一本相册' },
  { category: '纪念', title: '一起种一棵树' },
  { category: '纪念', title: '一起在硬币上刻字' },
  { category: '纪念', title: '一起买一对情侣项链' },
  { category: '纪念', title: '一起买一对情侣戒指' },
  { category: '纪念', title: '一起买一对情侣手链' },
  { category: '纪念', title: '一起穿一次情侣装' },
  { category: '纪念', title: '一起去看一场我们认识地点的旧地重游' },
  { category: '纪念', title: '一起在纸上写下五年后的样子' },
  { category: '纪念', title: '一起做一支告白短片' },
  { category: '纪念', title: '一起给彼此写一封 10 年后的信' },
  { category: '纪念', title: '一起在沙滩上写下名字拍照' },
  { category: '纪念', title: '一起在树上挂一个许愿牌' },
  { category: '纪念', title: '一起在地图上标记走过的城市' },
  { category: '纪念', title: '一起完成一次 100 题恋人问答' },
  { category: '纪念', title: '一起拍一次胶片照片' },
  { category: '纪念', title: '一起录一段语音备忘' },
  { category: '纪念', title: '一起认领一颗星星' },
  { category: '纪念', title: '一起把 LOGO 做成抱枕或杯子' },
  { category: '纪念', title: '一起合写一首诗' },
  { category: '纪念', title: '一起每年拍同款合影' },
  { category: '纪念', title: '一起庆祝一次三周年' },
  { category: '纪念', title: '一起为关系起一个专属代号' },
];

export const BUCKET_CATEGORIES = ['日常', '约会', '美食', '旅行', '惊喜', '成长', '挑战', '纪念'];
